name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

# GITHUB_TOKEN の権限
permissions:
  contents: read
  pages: write
  id-token: write
  # ※ artifacts API を直接呼ぶ場合は actions: write も付ける

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run build

      # Pages 用設定（必須ではないが推奨）
      - uses: actions/configure-pages@v5

      # v3 は upload-artifact@v4 を内部使用
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist      # ビルド成果物のディレクトリ

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
